### ISSUE TITLE
20210131verから20220503verのglbモデルの表示の変化

### ISSUE THREAD

**Issue by tdot0** [xelloss120/VRM_DollPlayPCver#26]
GLBモデルの表示が変わっており、一部はアルファクリップが正常に作用していなかったり、
マテリアルの設定がデフォルトに戻っているようです。
![e20162cb-192c-4afb-b8ab-2efb3dec5848](https://user-images.githubusercontent.com/56240220/166606439-ab32ee26-19b7-44cc-b696-b0b513cd79dd.png)
![ggg](https://user-images.githubusercontent.com/56240220/166608251-dcbd3238-8523-48cb-969b-91622df502ca.png)

**Comment by xelloss120** [comment]
詳細情報ありがとうございます。
私のポカミスならすぐ直りますが、GLB読み込み回りは特別変えてないハズので、UniVRM側で何か変化があったとすると、根が深い問題かもしれません。

**Comment by tdot0** [comment]
お返事いただきありがとうございます、UniVRM0.97.0の入っているUnityで読み込んだ場合20210131verと同じ表示になりますね。UniVRMではないかもしれません・・・？

**Comment by xelloss120** [comment]
直りました！（たぶん

参考
https://twitter.com/120byte/status/1521902491897454593

結果
https://twitter.com/120byte/status/1521902230789496832

DL
https://120byte.booth.pm/items/1654585

**Comment by tdot0** [comment]
素早い対応ありがとうございます！問題なく表示されるようになりました
![hhh](https://user-images.githubusercontent.com/56240220/166765751-a6719849-b6e6-4263-861d-78b8e6a63cee.png)
![000](https://user-images.githubusercontent.com/56240220/166769429-fe6b0e9e-a867-4ac1-8088-4034729f6f73.png)
